/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes the Connection API /single/receivers/{receiverId} base resource
 */
export type ConnectionAPISingleReceiversReceiverIdBaseResource = [
  "constraints/" | "staged/" | "active/" | "transporttype/",
  "constraints/" | "staged/" | "active/" | "transporttype/",
  "constraints/" | "staged/" | "active/" | "transporttype/",
  "constraints/" | "staged/" | "active/" | "transporttype/"
];
