/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Transport-specific parameters. If this parameter is included in a client request it must include the same number of array elements (or 'legs') as specified in the constraints. If no changes are required to a specific leg it must be included as an empty object ({}).
 */
export type ReceiverTransportParameters =
  | ReceiverInput[]
  | {
      [k: string]: unknown;
    }[]
  | ReceiverInput1[]
  | ReceiverInput2[];
/**
 * Describes external Receiver transport parameters defined in other AMWA specifications. The constraints in this schema are minimum constraints, but may be further constrained at the constraints endpoint.
 *
 * This interface was referenced by `ReceiverInput`'s JSON-Schema definition
 * via the `patternProperty` "^ext_[a-zA-Z0-9_]+$".
 *
 * This interface was referenced by `ReceiverInput1`'s JSON-Schema definition
 * via the `patternProperty` "^ext_[a-zA-Z0-9_]+$".
 *
 * This interface was referenced by `ReceiverInput2`'s JSON-Schema definition
 * via the `patternProperty` "^ext_[a-zA-Z0-9_]+$".
 */
export type ExternalReceiverTransportParameters = string | boolean | null | number;

/**
 * Describes a receiver
 */
export interface ReceiverResource {
  /**
   * ID of the Sender subscribed to by this Receiver. This will be null if the receiver has not been configured to receive anything, or if it is receiving from a non-NMOS sender.
   */
  sender_id?: string | null;
  /**
   * Master on/off control for receiver
   */
  master_enable?: boolean;
  activation?: ActivationResource;
  transport_file?: TransportFile;
  transport_params?: ReceiverTransportParameters;
}
/**
 * Parameters concerned with activation of the transport parameters
 */
export interface ActivationResource {
  /**
   * Mode of activation: immediate (on message receipt), scheduled_absolute (when internal clock >= requested_time), scheduled_relative (when internal clock >= time of message receipt + requested_time), or null (no activation scheduled)
   */
  mode: ("activate_immediate" | "activate_scheduled_absolute" | "activate_scheduled_relative") | null;
  /**
   * String formatted TAI timestamp (<seconds>:<nanoseconds>) indicating time (absolute or relative) for activation. Should be null or not present if 'mode' is null.
   */
  requested_time?: string | null;
}
/**
 * Transport file parameters. 'data' and 'type' must both be strings or both be null. If 'type' is non-null 'data' is expected to contain a valid instance of the specified media type.
 */
export interface TransportFile {
  /**
   * Content of the transport file
   */
  data: string | null;
  /**
   * IANA assigned media type for file (e.g application/sdp)
   */
  type: string | null;
}
/**
 * Describes RTP Receiver transport parameters. The constraints in this schema are minimum constraints, but may be further constrained at the constraints endpoint. Receivers must support at least the `source_ip`, `interface_ip`, `rtp_enabled` and `destination_port` parameters, and must support the `multicast_ip` parameter if they are capable of multicast operation. Receivers supporting FEC and/or RTCP must support parameters prefixed with `fec` and `rtcp` respectively.
 */
export interface ReceiverInput {
  /**
   * Source IP address of RTP packets in unicast mode, source filter for source specific multicast. A null value indicates that the source IP address has not been configured in unicast mode, or the Receiver is in any-source multicast mode.
   */
  source_ip?: (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
    | null
  ) &
    (
      | ((
          | {
              [k: string]: unknown;
            }
          | {
              [k: string]: unknown;
            }
          | null
        ) &
          string)
      | ((
          | {
              [k: string]: unknown;
            }
          | {
              [k: string]: unknown;
            }
          | null
        ) &
          null)
    );
  /**
   * IP multicast group address used in multicast operation only. Should be set to null during unicast operation. A null value indicates the parameter has not been configured, or the receiver is operating in unicast mode.
   */
  multicast_ip?: (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
    | null
  ) &
    (
      | ((
          | {
              [k: string]: unknown;
            }
          | {
              [k: string]: unknown;
            }
          | null
        ) &
          string)
      | ((
          | {
              [k: string]: unknown;
            }
          | {
              [k: string]: unknown;
            }
          | null
        ) &
          null)
    );
  /**
   * IP address of the network interface the receiver should use. The receiver should provide an enum in the constraints endpoint, which should contain the available interface addresses. If set to auto in multicast mode the receiver should determine which interface to use for itself, for example by using the routing tables. The behaviour of auto is undefined in unicast mode, and controllers should supply a specific interface address.
   */
  interface_ip?: (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
  ) &
    string;
  /**
   * destination port for RTP packets (auto = 5004 by default)
   */
  destination_port?: number | string;
  /**
   * FEC on/off
   */
  fec_enabled?: boolean;
  /**
   * May be used if NAT is being used at the destination (auto = multicast_ip (multicast mode) or interface_ip (unicast mode) by default)
   */
  fec_destination_ip?: (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
  ) &
    string;
  /**
   * forward error correction mode to apply. (auto = highest available number of dimensions by default)
   */
  fec_mode?: "auto" | "1D" | "2D";
  /**
   * destination port for RTP Column FEC packets (auto = RTP destination_port + 2 by default)
   */
  fec1D_destination_port?: number | string;
  /**
   * destination port for RTP Row FEC packets (auto = RTP destination_port + 4 by default)
   */
  fec2D_destination_port?: number | string;
  /**
   * Destination IP address of RTCP packets (auto = multicast_ip (multicast mode) or interface_ip (unicast mode) by default)
   */
  rtcp_destination_ip?: (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
  ) &
    string;
  /**
   * RTCP on/off
   */
  rtcp_enabled?: boolean;
  /**
   * destination port for RTCP packets (auto = RTP destination_port + 1 by default)
   */
  rtcp_destination_port?: number | string;
  /**
   * RTP reception active/inactive
   */
  rtp_enabled?: boolean;
  [k: string]: ExternalReceiverTransportParameters;
}
/**
 * Describes WebSocket Receiver transport parameters. The constraints in this schema are minimum constraints, but may be further constrained at the constraints endpoint. WebSocket Receivers must support all parameters in this schema.
 */
export interface ReceiverInput1 {
  /**
   * URI hosting the WebSocket server as defined in RFC 6455 Section 3. A null value indicates that the receiver has not yet been configured.
   */
  connection_uri?: ({
    [k: string]: unknown;
  } | null) &
    (
      | (({
          [k: string]: unknown;
        } | null) &
          string)
      | (({
          [k: string]: unknown;
        } | null) &
          null)
    );
  /**
   * Indication of whether authorization is required to make a connection. If the parameter is set to auto the Receiver should establish for itself whether authorization should be used, based on its own internal configuration.
   */
  connection_authorization?: ("auto" | true | false) | ("auto" | true | false);
  [k: string]: ExternalReceiverTransportParameters;
}
/**
 * Describes MQTT Receiver transport parameters. The constraints in this schema are minimum constraints, but may be further constrained at the constraints endpoint. MQTT Receivers must support all parameters in this schema.
 */
export interface ReceiverInput2 {
  /**
   * Hostname or IP hosting the MQTT broker. If the parameter is set to auto the Receiver should establish for itself which broker it should use, based on a discovery mechanism or its own internal configuration. A null value indicates that the Receiver has not yet been configured.
   */
  source_host?: (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
    | null
  ) &
    (
      | ((
          | {
              [k: string]: unknown;
            }
          | {
              [k: string]: unknown;
            }
          | {
              [k: string]: unknown;
            }
          | {
              [k: string]: unknown;
            }
          | null
        ) &
          string)
      | ((
          | {
              [k: string]: unknown;
            }
          | {
              [k: string]: unknown;
            }
          | {
              [k: string]: unknown;
            }
          | {
              [k: string]: unknown;
            }
          | null
        ) &
          null)
    );
  /**
   * Source port for MQTT traffic. If the parameter is set to auto the Receiver should establish for itself which broker it should use, based on a discovery mechanism or its own internal configuration.
   */
  source_port?: number | string;
  /**
   * Indication of whether TLS is used for communication with the broker. 'mqtt' indicates operation without TLS, and 'secure-mqtt' indicates use of TLS. If the parameter is set to auto the Receiver should establish for itself which protocol it should use, based on a discovery mechanism or its own internal configuration.
   */
  broker_protocol?: "auto" | "mqtt" | "secure-mqtt";
  /**
   * Indication of whether authorization is used for communication with the broker. If the parameter is set to auto the Receiver should establish for itself whether authorization should be used, based on a discovery mechanism or its own internal configuration.
   */
  broker_authorization?: ("auto" | true | false) | ("auto" | true | false);
  /**
   * The topic which MQTT messages will be received from via the MQTT broker. A null value indicates that the Receiver has not yet been configured.
   */
  broker_topic?: string | null;
  /**
   * The topic used for MQTT status messages such as MQTT Last Will which are received via the MQTT broker. A null value indicates that the Receiver has not yet been configured, or is not using a connection status topic.
   */
  connection_status_broker_topic?: string | null;
  [k: string]: ExternalReceiverTransportParameters;
}
