/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Transport type URN base used by the Sender or Receiver (i.e. with any subclassifications or versions removed)
 */
export type TransportType = TransportType1 & TransportType2;
export type TransportType1 =
  | "urn:x-nmos:transport:rtp"
  | "urn:x-nmos:transport:dash"
  | "urn:x-nmos:transport:websocket"
  | "urn:x-nmos:transport:mqtt";
export type TransportType2 = string;
